# These are supported funding model platforms

github: [abhinavshr]   # Your GitHub Sponsors username (if enabled)
patreon: abhinavshr    # Your Patreon username
open_collective:       # Leave empty if not using
ko_fi: abhinavshr      # Your Ko-fi username
tidelift:
community_bridge:
liberapay:
issuehunt:
lfx_crowdfunding:
polar:
buy_me_a_coffee: abhinavshr  # Your Buy Me a Coffee username
thanks_dev:
custom: ['https://aichat-git-main-abhinavshrs-projects.vercel.app']  # Any custom link you want
